language: node_js

node_js: stable

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g
    - npm install hexo -g

install:
    - npm install

script:
    - hexo clean

after_script:
    - set -ev

    - git clone https://${GH_REF} build_hexo
    - cd build_hexo
    - git checkout hexo
    - hexo g -d

branches:
    only:
        - hexo

env:
    global:
        - GH_REF: github.com/tzzs/tzzs.github.io.git
